version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: graceful
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DOMAIN: localhost
      ENVIRONMENT: local
      PROJECT_NAME: "Full Stack FastAPI Project"
      STACK_NAME: full-stack-fastapi-project
      BACKEND_CORS_ORIGINS: "http://localhost,http://localhost:5173,https://localhost,https://localhost:5173"
      SECRET_KEY: 12345678
      FIRST_SUPERUSER: devops@hng.tech
      FIRST_SUPERUSER_PASSWORD: devops#HNG11
      USERS_OPEN_REGISTRATION: "True"
      EMAILS_FROM_EMAIL: info@example.com
      SMTP_HOST: ""
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      SMTP_TLS: "True"
      SMTP_SSL: "False"
      SMTP_PORT: "587"
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: graceful
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://backend:8000

volumes:
  postgres_data:
